# Generated by Django 5.1

import uuid
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CurrencySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('base_currency', models.CharField(default='EUR', help_text='ISO 4217 code for the base currency', max_length=3, verbose_name='Base Currency')),
                ('auto_update_rates', models.BooleanField(default=False, verbose_name='Auto-update Rates')),
                ('update_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10, verbose_name='Update Frequency')),
                ('rate_source', models.CharField(choices=[('manual', 'Manual'), ('ecb', 'European Central Bank'), ('exchangerate_api', 'ExchangeRate API')], default='manual', max_length=20, verbose_name='Rate Source')),
                ('api_key', models.CharField(blank=True, help_text='API key for the exchange rate provider', max_length=255, verbose_name='API Key')),
                ('round_to_decimals', models.IntegerField(default=2, verbose_name='Round to Decimals')),
                ('show_both_currencies', models.BooleanField(default=True, help_text='Show base + foreign currency on receipt', verbose_name='Show Both Currencies')),
                ('allow_multi_currency_payment', models.BooleanField(default=True, verbose_name='Allow Multi-Currency Payment')),
            ],
            options={
                'verbose_name': 'Currency Settings',
                'verbose_name_plural': 'Currency Settings',
                'db_table': 'multicurrency_settings',
                'abstract': False,
                'unique_together': {('hub_id',)},
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('code', models.CharField(help_text='ISO 4217 code, e.g. USD', max_length=3, verbose_name='Currency Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('decimal_places', models.IntegerField(default=2, verbose_name='Decimal Places')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Rate vs base currency', max_digits=12, verbose_name='Exchange Rate')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Last Updated')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'multicurrency_currency',
                'ordering': ['sort_order', 'code'],
                'abstract': False,
                'unique_together': {('hub_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Exchange Rate')),
                ('source', models.CharField(help_text='manual/ecb/api', max_length=50, verbose_name='Source')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Recorded At')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='multicurrency.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Exchange Rate History',
                'verbose_name_plural': 'Exchange Rate History',
                'db_table': 'multicurrency_rate_history',
                'ordering': ['-recorded_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='exchangeratehistory',
            index=models.Index(fields=['currency', '-recorded_at'], name='multicurren_currenc_idx'),
        ),
        migrations.CreateModel(
            name='CurrencyPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('sale_id', models.UUIDField(blank=True, help_text='FK to sale', null=True, verbose_name='Sale')),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Amount in foreign currency', max_digits=10, verbose_name='Original Amount')),
                ('exchange_rate_used', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Exchange Rate Used')),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Converted to base currency', max_digits=10, verbose_name='Base Amount')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Payment Date')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='multicurrency.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Currency Payment',
                'verbose_name_plural': 'Currency Payments',
                'db_table': 'multicurrency_payment',
                'ordering': ['-payment_date'],
                'abstract': False,
            },
        ),
    ]
