# Generated by Django 6.0.1 on 2026-02-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multicurrency', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exchangeratehistory',
            new_name='multicurren_currenc_17b132_idx',
            old_name='multicurren_currenc_idx',
        ),
    ]
